# Generated by Django 5.0.3 on 2024-04-01 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inner', 'Inner'), ('outer', 'Outer')], max_length=6)),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cost', models.FloatField()),
                ('hourly_increase', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('Slot_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parkinglots')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('expiry', models.DateTimeField()),
                ('Slot_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parkinglots')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.consumer')),
            ],
        ),
    ]
