# Generated by Django 5.0.3 on 2024-04-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_parkinglots_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglots',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
